"""0002_chat_messages

Revision ID: 04eea7cae321
Revises: 4577658a2894
Create Date: 2026-08-19 23:03:43.157368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04eea7cae321'
down_revision: Union[str, None] = '4577658a2894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级：执行迁移变更（创建表/索引/字段）。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sender', sa.String(length=10), nullable=False),
    sa.Column('admin_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read_admin', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_read_user', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='前台用户与后台管理员聊天消息'
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_admin_unread', ['sender', 'is_read_admin'], unique=False)
        batch_op.create_index('ix_chat_user_created', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚：撤销升级变更（顺序与 upgrade 相反）。"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_user_created')
        batch_op.drop_index('ix_chat_admin_unread')

    op.drop_table('chat_messages')
    # ### end Alembic commands ###
