"""0004_about_workshop

Revision ID: 3ffb5adf9772
Revises: 53265803e51f
Create Date: 2026-08-21 09:42:37.963558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ffb5adf9772'
down_revision: Union[str, None] = '53265803e51f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级：执行迁移变更（创建表/索引/字段）。"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workshop', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='[]', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚：撤销升级变更（顺序与 upgrade 相反）。"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.drop_column('workshop')

    # ### end Alembic commands ###
