"""0001_initial 创建 11 张表

Revision ID: 4577658a2894
Revises: 
Create Date: 2026-08-19 14:28:23.658651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4577658a2894'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级：执行迁移变更（创建表/索引/字段）。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about',
    sa.Column('company_intro', sa.Text(), nullable=True),
    sa.Column('brand_story', sa.Text(), nullable=True),
    sa.Column('honors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('selling_points', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='关于我们配置（单行）'
    )
    op.create_table('banners',
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=512), nullable=False),
    sa.Column('link_url', sa.String(length=512), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_activate', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='轮播图'
    )
    op.create_table('categories',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('cover_image', sa.String(length=512), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='品类（系列）'
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index('uk_categories_slug', ['slug'], unique=True)

    op.create_table('departments',
    sa.Column('dept_name', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='后台部门'
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_parent_id'), ['parent_id'], unique=False)

    op.create_table('news',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('cover_image', sa.String(length=512), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_top', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_activate', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='新闻资讯'
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index('ix_news_publish', ['publish_date', 'is_activate', 'is_deleted'], unique=False)

    op.create_table('roles',
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='后台角色'
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('uk_roles_name', ['role_name'], unique=True)

    op.create_table('settings',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='系统设置（键值对）'
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index('uk_settings_key', ['key'], unique=True)

    op.create_table('users',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='注册会员（前台）'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('uk_users_phone', ['phone'], unique=True)

    op.create_table('admins',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('post', sa.String(length=50), nullable=True),
    sa.Column('dept_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('role_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='后台用户（超管）'
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_dept_id'), ['dept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admins_role_id'), ['role_id'], unique=False)
        batch_op.create_index('uk_admins_username', ['username'], unique=True)

    op.create_table('products',
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('series', sa.String(length=50), nullable=True),
    sa.Column('product_no', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('cover_image', sa.String(length=512), nullable=True),
    sa.Column('product_images', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('box_images', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('spec_params', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('spec', sa.String(length=100), nullable=True),
    sa.Column('flavor', sa.String(length=100), nullable=True),
    sa.Column('ingredients', sa.Text(), nullable=True),
    sa.Column('net_weight', sa.String(length=50), nullable=True),
    sa.Column('shelf_life', sa.String(length=50), nullable=True),
    sa.Column('storage', sa.String(length=100), nullable=True),
    sa.Column('allergen', sa.String(length=200), nullable=True),
    sa.Column('box_spec', sa.String(length=200), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('publish_status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='糕点礼盒'
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index('ix_products_publish_deleted', ['publish_status', 'is_deleted'], unique=False)
        batch_op.create_index('uk_products_no', ['product_no'], unique=True)

    op.create_table('purchase_intents',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('requirement', sa.Text(), nullable=True),
    sa.Column('quantity_range', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('is_activate', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='团购/定制意向'
    )
    with op.batch_alter_table('purchase_intents', schema=None) as batch_op:
        batch_op.create_index('ix_purchase_created', ['created_at'], unique=False)
        batch_op.create_index('ix_purchase_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚：撤销升级变更（顺序与 upgrade 相反）。"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_intents', schema=None) as batch_op:
        batch_op.drop_index('ix_purchase_status')
        batch_op.drop_index('ix_purchase_created')

    op.drop_table('purchase_intents')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('uk_products_no')
        batch_op.drop_index('ix_products_publish_deleted')
        batch_op.drop_index(batch_op.f('ix_products_category_id'))

    op.drop_table('products')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index('uk_admins_username')
        batch_op.drop_index(batch_op.f('ix_admins_role_id'))
        batch_op.drop_index(batch_op.f('ix_admins_dept_id'))

    op.drop_table('admins')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('uk_users_phone')

    op.drop_table('users')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index('uk_settings_key')

    op.drop_table('settings')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('uk_roles_name')

    op.drop_table('roles')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index('ix_news_publish')

    op.drop_table('news')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_parent_id'))

    op.drop_table('departments')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('uk_categories_slug')

    op.drop_table('categories')
    op.drop_table('banners')
    op.drop_table('about')
    # ### end Alembic commands ###
