"""0003_intent_product

Revision ID: 53265803e51f
Revises: 04eea7cae321
Create Date: 2026-08-20 14:10:06.998758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53265803e51f'
down_revision: Union[str, None] = '04eea7cae321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级：执行迁移变更（创建表/索引/字段）。"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_intents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True))
        batch_op.create_index(batch_op.f('ix_purchase_intents_product_id'), ['product_id'], unique=False)
        # 修复：SQLite batch 模式外键约束必须命名（None 会报 Constraint must have a name）
        batch_op.create_foreign_key('fk_purchase_intents_product_id', 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚：撤销升级变更（顺序与 upgrade 相反）。"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_intents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_purchase_intents_product_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_purchase_intents_product_id'))
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
